approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d
npmPreapprovedPackages:
  - '@speckle/objectloader'
  - '@speckle/objectsender'
  - '@speckle/shared'

npmScopes:
  speckle:
    npmRegistryServer: 'https://npmregistry.mermaid-emperor.ts.net'
