name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # other running workflows get cancelled on the same branch

permissions: {} # purposefully empty by default at workflow level, explicitly overridden for specific jobs below

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with: {}
    secrets: {}
    permissions:
      contents: read

  lint:
    uses: ./.github/workflows/lint.yml
    with: {}
    secrets: {}
    permissions:
      contents: read

  build:
    needs:
      - get-version
    uses: ./.github/workflows/build.yml
    with:
      PUBLISH: false
      IMAGE_VERSION_TAG: ${{ needs.get-version.outputs.IMAGE_VERSION_TAG }}
    secrets: {}
    permissions:
      contents: read
      packages: write # the workflow fragment requires this as it has the capability to publish, even though the logic prevents publishing
